language: node_js
node_js:
- '0.12'
before_install:
- npm install npm -g
before_script:
- npm install
script: npm run ci
addons:
  sauce_connect: true
env:
  global:
    - secure: OiqxxRgpEe+0kZOlmPYPdeA68KpXRcdMHlsSy3o01kdqv+Mzy9vmUDjjpaWVSquFa7+BMDVD1q34/NPU3Nbj0cdZBTsDJwxebeHKL+7IHab21HPZSajQBc0AcXLKZ7bkCQZXaR/n+mSLCHMV0tHJQ51L287LDUABkBnBAkdvba12gTXurc84OklC8V8bUAYc8j5OeEUkT/cgGdDTQnvyVjWUwIgM0kNb7qCK6xWtkpphsVrbPdagu0PRYI/B8rcOZPLm9BlC2LUmtttOIWeruLU49aMeuxAxWNfADGx0pT4EZJngW3QWrYyYEHV8KlhhbVSd0ycb8OYK304F2b2xVq4UhnqpFXc8xJbse/KioWNwOWngS18CRL+gnI1YC1EPqT/KwuOEHGm8tDkCLSXVJpvTo1YMf7vl+mzT2Mdap/1nsnBn7qpoQnWCTd2m9e4oV3GdrttieLmDmmbVgOG6F3adBOZMro5eKthVNqwmVpWtn/Ti6JAHMHNEs7ZM6H0PJuG+gPGBuyO4uCakFJS2COrSTc7tSs/tOg1/BPq2UsAxPrccq9dhIfeGAL0LzcinGJ0ceeyo21TCuCvjibfhBiNOqJIznHrsZjCnNR1x3cp3ZqgL4+GwAZ1r5vgvvH6dBP0JOdzrurKfaMBn2qsR4MvykpDvbjkT3/Rd70NkhdA=
    - secure: mPH/UOshvr9M5Ksu/Ok9pS9yBAnDoEPJD93zjpyd64n3W84pyRsr+K68nKBmEr3I5UlCxBBvcOcRy1XRnZw/gEq/WccxOesZrqQwGpWDn7WWVlEU3orqMlu6KSmtT6jl35pzrS7O0dEliop5Ehq3YbASmSx+9CxH3ScXxYthsgRhKTcUPSPP7rchzCkiiJrGpeMuaFxLMiUGe1EhW67YNKWA4bjqUGGsArOOcqpX8L5VyQceP4HlG17q4d51ioKEKHIDbjPiFfQMYFf+Cn4vRIS4MwLi3z28/k+dYi9qsV9OrHtcMCCaKdsdY2S1MRFpAV/n2NphWbp0j0lk56Wn9NwYPHYVQ0ZfXxp+TM2qgmSRA9U7kFxjuydS4uldAifmeFGhR+8eKaDp3dXFM/MQuBb12iQoMB2u+RW5InM+sxqKxdU6S+NWhuopqRTiWUHl4v94aceHyqMWtZgFAnyD7DtVVFIZUroAge5RXRCGCSLfBMPly3RWMz9XDW4dh5zP2fHmb+dpq6wavzx9Yj1S/QMBPRg0LgVR2A8RQfCgoXJ3tSRaN0CzCm0MsM317AsHQAVz+Amb3SQxtbnroLRCRjidl6HXCOnMTV1t8x/97MvVrGqN8PbaMT4RIdVy2ZywT9BKezCcJM+cHraxOfOqFy0t0VyNk7rSACDc522yU8o=
